version: '2'

services:
  solr-node1:
    image: bitnami/solr:latest
    restart: always
    ports:
      - '8983:8983'
    environment:
      - SOLR_ENABLE_AUTHENTICATION=yes
      - SOLR_ADMIN_USERNAME=${SOLR_ADMIN_USERNAME}
      - SOLR_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SOLR_CORES=my_core
    volumes:
      - ./data:/var/data/solr