version: '3'
services:
  solr:
    image: solr:latest
    restart: always
    ports:
     - "172.17.0.1:8983:8983"
    volumes:
      - ./data:/var/solr
    command:
      - solr-precreate
      - gettingstarted